### ISSUE TITLE
[Help] Cannot execute binary file.

### ISSUE THREAD

**Issue by fenixdoido** [m33b0/mass-deauth#1]
Im trying to execute this script on my Kali Sana Light but I can't run it.
It works fine on the full version of Kali.

![img_20151226_130711](https://cloud.githubusercontent.com/assets/12750143/12006905/ca776e90-abd1-11e5-8566-af3e3500558e.jpg)

**Comment by m33b0** [comment]
Probably missing a dependency of some sort. Works just fine on my Linux boxes. Some more information would be helpful. Like an strace or something.
